# vim: set ft=tmux:

# configure tmux-battery
set -g @batt_icon_charge_tier8 "󰁹"
set -g @batt_icon_charge_tier7 "󰂁"
set -g @batt_icon_charge_tier6 "󰁿"
set -g @batt_icon_charge_tier5 "󰁾"
set -g @batt_icon_charge_tier4 "󰁽"
set -g @batt_icon_charge_tier3 "󰁼"
set -g @batt_icon_charge_tier2 "󰁻"
set -g @batt_icon_charge_tier1 "󰁺"
set -g @batt_icon_status_charged "󰚥"
set -g @batt_icon_status_charging "󰂄"
set -g @batt_icon_status_discharging "󰂃"
set -g @batt_icon_status_unknown "󰂑"
set -g @batt_icon_status_attached "󱈑"

# run battery_enabled for `@battery_exists`
if "test -f ~/.config/tmux/plugins/tmux-battery/battery_enabled.tmux" "run ~/.config/tmux/plugins/tmux-battery/battery_enabled.tmux"

# configure tmux-cpu
set -g @cpu_low_icon "󰍛"
set -g @cpu_medium_icon "󰍛"
set -g @cpu_high_icon "󰍛"
set -g @cpu_low_fg_color "#[fg=#{@thm_sky}]"
set -g @cpu_medium_fg_color "#[fg=#{@thm_peach}]"
set -g @cpu_high_fg_color "#[fg=#{@thm_red}]"
set -g @cpu_low_bg_color "#[bg=#{@thm_bg}]"
set -g @cpu_medium_bg_color "#[bg=#{@thm_bg}]"
set -g @cpu_high_bg_color "#[bg=#{@thm_bg}]"
set -g @cpu_percentage_format "%2.0f%%"
set -g @cpu_medium_thresh "40"
set -g @cpu_high_thresh "80"

set -g @gpu_low_icon "󰢮"
set -g @gpu_medium_icon "󰢮"
set -g @gpu_high_icon "󰢮"
set -g @gpu_low_fg_color "#[fg=#{@thm_sky}]"
set -g @gpu_medium_fg_color "#[fg=#{@thm_peach}]"
set -g @gpu_high_fg_color "#[fg=#{@thm_red}]"
set -g @gpu_low_bg_color "#[bg=#{@thm_bg}]"
set -g @gpu_medium_bg_color "#[bg=#{@thm_bg}]"
set -g @gpu_high_bg_color "#[bg=#{@thm_bg}]"
set -g @gpu_percentage_format "%2.0f%%"
set -g @gpu_medium_thresh "50"
set -g @gpu_high_thresh "80"

set -g @ram_low_icon "󰘚"
set -g @ram_medium_icon "󰘚"
set -g @ram_high_icon "󰘚"
set -g @ram_low_fg_color "#[fg=#{@thm_sky}]"
set -g @ram_medium_fg_color "#[fg=#{@thm_peach}]"
set -g @ram_high_fg_color "#[fg=#{@thm_red}]"
set -g @ram_low_bg_color "#[bg=#{@thm_bg}]"
set -g @ram_medium_bg_color "#[bg=#{@thm_bg}]"
set -g @ram_high_bg_color "#[bg=#{@thm_bg}]"
set -g @ram_percentage_format "%2.0f%%"
set -g @ram_medium_thresh "60"
set -g @ram_high_thresh "90"

# configure Catppuccin
# the design is taken from https://github.com/catppuccin/tmux/discussions/317#discussioncomment-11064512
set -g @catppuccin_flavor "mocha"

# > Make sure you load the catppuccin theme prior to setting the status-left and/or status-* options.
# > This ensures the catppuccin options (such as colors and status modules) are defined so they can then be used.
# see: https://github.com/catppuccin/tmux/blob/main/docs/reference/status-line.md#notes-for-tpm-users
# > Make sure any line with `set -g @catpuccin*` is before you run the plugin
# see: https://github.com/catppuccin/tmux/issues/458#issuecomment-2579985228
run ~/.config/tmux/plugins/tmux/catppuccin.tmux

